spring.config.import: vault://
spring.cloud.vault:
  authentication: TOKEN
  token: azerty12345
  uri: http://localhost:8200
  kv:
    enabled: true
    backend: secret
    application-name: poc-vault
  database:
    enabled: true
    backend: database
    role: admin
spring.datasource:
  url: jdbc:postgresql://localhost:5432/formation_spring